src/objects/Company_Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>ReportTime__c</fullName>
        <label>Report Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StartDay__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>TimeSheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Users TimeSheets</relationshipLabel>
        <relationshipName>Users_TimeSheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User TimeSheet</label>
    <nameField>
        <displayFormat>UTS-{00000000}</displayFormat>
        <label>User TimeSheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users TimeSheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vacation_Days__c.object
<CustomObject>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Vacation Days</relationshipLabel>
        <relationshipName>Vacation_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacation_Day__c</fullName>
        <label>Vacation Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Vacation Day</label>
    <nameField>
        <displayFormat>VD-{0000}</displayFormat>
        <label>Vacation Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EE_TEST_CTRL_UserTimeSheetExtension.cls
@isTest
public class EE_TEST_CTRL_UserTimeSheetExtension {

	private static final String SUCCESS = 'success';

	@testSetup
	static void init(){
		insert EE_UTL_TestUtils.getTimeSheetConfiguration();
	}

	private static EE_CTRL_UserTimeSheetExtension getExtension(User_TimeSheet__c record){
		ApexPages.StandardController stdController = new ApexPages.StandardController(record);
		EE_CTRL_UserTimeSheetExtension extension = new EE_CTRL_UserTimeSheetExtension(stdController);
		return extension;
	}

	@isTest
	static void userTimeSheetCreatedTest(){
		Company_Project__c project = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		TimeSheet__c timeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();

		Test.startTest();

		PageReference tsPage = Page.EE_UserTimeSheet;
		Test.setCurrentPageReference(tsPage);
		ApexPages.currentPage().getParameters().put('tsId',timeSheet.ID);
		ApexPages.currentPage().getParameters().put('projectId',project.ID);

		EE_CTRL_UserTimeSheetExtension extension = getExtension(new User_TimeSheet__c());
		PageReference pageRef = extension.saveUserTimeSheet();

		System.assertEquals(SUCCESS,pageRef.getParameters().get('msg'));
		System.assertEquals(extension.userTimeSheet.ID,pageRef.getParameters().get('id'));

		Test.stopTest();
	}

	@isTest
	static void userTimeSheetCreatedAndSendTest(){
		Company_Project__c project = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		TimeSheet__c timeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();

		Test.startTest();

		PageReference tsPage = Page.EE_UserTimeSheet;
		Test.setCurrentPageReference(tsPage);
		ApexPages.currentPage().getParameters().put('tsId',timeSheet.ID);
		ApexPages.currentPage().getParameters().put('projectId',project.ID);

		EE_CTRL_UserTimeSheetExtension extension = getExtension(new User_TimeSheet__c());
		PageReference pageRef = extension.saveUserTimeSheet();
		Test.setCurrentPageReference(pageRef);
		extension.sentForApproval();

		System.assertEquals(EE_SRV_TimeSheetManager.SENT_STATUS,extension.userTimeSheet.Status__c);

		Test.stopTest();
	}

	@isTest
	static void userTimeSheetOverdueTest(){
		Company_Project__c project = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		TimeSheet__c timeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();
		timeSheet.ReportTime__c = Datetime.newInstance(1970,1,14);
		update timeSheet;

		Test.startTest();

		PageReference tsPage = Page.EE_UserTimeSheet;
		Test.setCurrentPageReference(tsPage);
		ApexPages.currentPage().getParameters().put('tsId',timeSheet.ID);
		ApexPages.currentPage().getParameters().put('projectId',project.ID);

		EE_CTRL_UserTimeSheetExtension extension = getExtension(new User_TimeSheet__c());
		System.assert(extension.getDisableSaveButton());
		System.assertEquals(EE_SRV_TimeSheetManager.OVERDUE_STATUS,extension.userTimeSheet.Status__c);

		PageReference pageRef = extension.saveUserTimeSheet();
		System.assertEquals(null,pageRef);

		extension.saveOverdueUserTimeSheet();
		System.assert(extension.redirectAfterOverdueCheck);

		Test.stopTest();
	}

	@isTest
	static void sentForApprovalAndApprovedTest(){
		Company_Project__c project = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		TimeSheet__c timeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();

		Test.startTest();

		PageReference tsPage = Page.EE_UserTimeSheet;
		Test.setCurrentPageReference(tsPage);
		ApexPages.currentPage().getParameters().put('tsId',timeSheet.ID);
		ApexPages.currentPage().getParameters().put('projectId',project.ID);

		EE_CTRL_UserTimeSheetExtension extension = getExtension(new User_TimeSheet__c());

		PageReference pageRef = extension.saveUserTimeSheet();
		System.assertNotEquals(null,pageRef);

		Test.setCurrentPageReference(pageRef);
		Id savedTsId = ApexPages.currentPage().getParameters().get('id');
		User_TimeSheet__c savedTs = EE_DAO_TimeSheetDao.getUserTimeSheetById(savedTsId);
		extension = getExtension(savedTs);
		extension.sentForApproval();

		System.assertEquals(EE_SRV_TimeSheetManager.SENT_STATUS,extension.userTimeSheet.Status__c);
		System.assert(extension.userTimeSheet.Previously_Sent__c);

		extension.userTimeSheet.Status__c = EE_SRV_TimeSheetManager.APPROVED_STATUS;
		update extension.userTimeSheet;

		savedTS = EE_DAO_TimeSheetDao.getUserTimeSheetById(extension.userTimeSheet.ID);
		extension = getExtension(savedTs);
		System.assert(extension.getDisableSaveButton());
		extension.saveUserTimeSheet();
		System.assertEquals(EE_SRV_TimeSheetManager.APPROVED_STATUS,extension.userTimeSheet.Status__c);
		System.assert(extension.userTimeSheet.Previously_Sent__c);

		Test.stopTest();
	}

	@isTest
	static void rejectedAndApprovedTest(){
		Company_Project__c project = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		TimeSheet__c timeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();

		Test.startTest();

		PageReference tsPage = Page.EE_UserTimeSheet;
		Test.setCurrentPageReference(tsPage);
		ApexPages.currentPage().getParameters().put('tsId',timeSheet.ID);
		ApexPages.currentPage().getParameters().put('projectId',project.ID);

		EE_CTRL_UserTimeSheetExtension extension = getExtension(new User_TimeSheet__c());

		PageReference pageRef = extension.saveUserTimeSheet();
		System.assertNotEquals(null,pageRef);

		Test.setCurrentPageReference(pageRef);
		Id savedTsId = ApexPages.currentPage().getParameters().get('id');
		User_TimeSheet__c savedTs = EE_DAO_TimeSheetDao.getUserTimeSheetById(savedTsId);

		extension = getExtension(savedTs);
		extension.sentForApproval();
		System.assertEquals(EE_SRV_TimeSheetManager.SENT_STATUS,extension.userTimeSheet.Status__c);

		extension.userTimeSheet.Status__c = EE_SRV_TimeSheetManager.REJECTED_STATUS;
		update extension.userTimeSheet;

		savedTS = EE_DAO_TimeSheetDao.getUserTimeSheetById(extension.userTimeSheet.ID);
		extension = getExtension(savedTs);
		System.assert(!extension.getDisableSaveButton());
		pageRef = extension.saveUserTimeSheet();
		System.assertEquals(EE_SRV_TimeSheetManager.SUBMITTED_STATUS,extension.userTimeSheet.Status__c);

		Test.setCurrentPageReference(pageRef);
		savedTsId = ApexPages.currentPage().getParameters().get('id');
		savedTS = EE_DAO_TimeSheetDao.getUserTimeSheetById(savedTsId);
		extension = getExtension(savedTs);
		extension.sentForApproval();
		System.assertEquals(EE_SRV_TimeSheetManager.SENT_STATUS,extension.userTimeSheet.Status__c);

		extension.userTimeSheet.Status__c = EE_SRV_TimeSheetManager.APPROVED_STATUS;
		update extension.userTimeSheet;

		savedTS = EE_DAO_TimeSheetDao.getUserTimeSheetById(extension.userTimeSheet.ID);
		extension = getExtension(savedTs);
		extension.saveUserTimeSheet();
		System.assertEquals(EE_SRV_TimeSheetManager.APPROVED_STATUS,extension.userTimeSheet.Status__c);
		Test.stopTest();
	}

	@isTest
	static void vacationDaysTest(){
		Company_Project__c project = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		TimeSheet__c timeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();
		List<Vacation_Days__c> vacationDays = EE_UTL_TestUtils.initDefaultVacationDaysForTimeSheet(timeSheet);
		insert vacationDays;

		Test.startTest();
		PageReference tsPage = Page.EE_UserTimeSheet;
		Test.setCurrentPageReference(tsPage);
		ApexPages.currentPage().getParameters().put('tsId',timeSheet.ID);
		ApexPages.currentPage().getParameters().put('projectId',project.ID);

		EE_CTRL_UserTimeSheetExtension extension = getExtension(new User_TimeSheet__c());

		for(Vacation_Days__c vacationDay:vacationDays){
			Integer vacationWeekDay = EE_UTL_DateUtils.getWeekDayOfVacationDay(extension.timeSheet.StartDay__c,vacationDay.Vacation_Day__c);
			System.assert(extension.vacationDays.contains(vacationWeekDay));
		}

		System.assertEquals(25,extension.getItems().size());

		Test.stopTest();
	}

}