src/objects/Company_Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeSheet__c.object
<CustomObject>
    <label>TimeSheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Users TimeSheets</relationshipLabel>
        <relationshipName>Users_TimeSheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User TimeSheet</label>
    <nameField>
        <displayFormat>UTS-{00000000}</displayFormat>
        <label>User TimeSheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users TimeSheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vacation_Days__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Vacation Days</relationshipLabel>
        <relationshipName>Vacation_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacation_Day__c</fullName>
        <label>Vacation Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Vacation Day</label>
    <nameField>
        <displayFormat>VD-{0000}</displayFormat>
        <label>Vacation Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EE_Test_UserTimeSheetUnit.cls
@isTest
public class EE_Test_UserTimeSheetUnit {

	public Company_Project__c unitProject {get;set;}

	public TimeSheet__c unitTimeSheet {get;set;}

	public PageReference currentPage {get;set;}

	public EE_CTRL_UserTimeSheetExtension extension {get;set;}

	public EE_Test_UserTimeSheetUnit(){
		unitProject = EE_UTL_TestUtils.initTestUserAndProjectAssociation('Test Project');
		unitTimeSheet = EE_UTL_TestUtils.initDefaultTimeSheet();

		setCurrentTestPage(getPageReference());
	}

	private void recreatePage(){
		setCurrentTestPage(getPageReference());
		addParameterToPage('id',extension.userTimeSheet.ID);
		recreateExtension(extension.userTimeSheet);
	}

	public PageReference getPageReference(){
		return Page.EE_UserTimeSheet;
	}

	public void addParameterToPage(String key,String value){
		ApexPages.currentPage().getParameters().put(key,value);
	}

	public void setCurrentTestPage(PageReference testPage){
		currentPage = testPage;
		Test.setCurrentPageReference(currentPage);
	}

	public EE_CTRL_UserTimeSheetExtension recreateExtension(User_TimeSheet__c record){
		ApexPages.StandardController stdController = new ApexPages.StandardController(record);
		EE_CTRL_UserTimeSheetExtension extension = new EE_CTRL_UserTimeSheetExtension(stdController);
		return extension;
	}

	public void initNewExtension(){
		extension = recreateExtension(new User_TimeSheet__c());
	}

	public PageReference save(){
		PageReference saveReference = extension.saveUserTimeSheet();
		System.debug(saveReference);
		if(saveReference != null) {
			setCurrentTestPage(saveReference);
			User_TimeSheet__c userTimeSheet = EE_DAO_TimeSheetDao.getUserTimeSheetById(extension.userTimeSheet.ID);
			extension = recreateExtension(userTimeSheet);
		}

		return saveReference;
	}

	public void sentForApproval(){
		extension.sentForApproval();
	}

	public void saveOverdue(){
		extension.saveOverdueUserTimeSheet();
	}

	public Boolean isRedirectAfterOverdueCheck(){
		return extension.redirectAfterOverdueCheck;
	}

	public void approveUserTimeSheet(){
		extension.userTimeSheet.Status__c =  EE_SRV_TimeSheetManager.APPROVED_STATUS;
		upsert extension.userTimeSheet;
		recreatePage();
	}

	public void rejectUserTimeSheet(){
		extension.userTimeSheet.Status__c =  EE_SRV_TimeSheetManager.REJECTED_STATUS;
		upsert extension.userTimeSheet;
		recreatePage();
	}

	public String getCurrentUserTimeSheetStatus(){
		return extension.userTimeSheet.Status__c;
	}

	public List<Vacation_Days__c> initVacationDays(){
		List<Vacation_Days__c> vacationDays = EE_UTL_TestUtils.initDefaultVacationDaysForTimeSheet(unitTimeSheet);
		insert vacationDays;

		return vacationDays;
	}

	public Vacation_Days__c createVacationDay(Date vacationDay){
		Vacation_Days__c vacation = new Vacation_Days__c(TimeSheet__c = unitTimeSheet.ID,Country__c = 'PL'
				,Vacation_Day__c = vacationDay);

		return vacation;
	}
}