src/objects/Company_Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company_Project_Assigment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Company_Project__c</referenceTo>
        <relationshipLabel>User Assigments</relationshipLabel>
        <relationshipName>Project_Assigments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assigments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assigment</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Project Assigment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Assigments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>FridayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MondayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SaturdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDay__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SundayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ThursdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TuesdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WednesdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday Included</label>
        <type>Checkbox</type>
    </fields>
    <label>TimeSheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Friday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Friday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Monday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overhours_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overhours Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Saturday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Saturday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sunday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sunday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thursday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Thursday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Users TimeSheets</relationshipLabel>
        <relationshipName>Users_TimeSheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tuesday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tuesday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Comment__c</fullName>
        <label>User Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Users_TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wednesday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Wednesday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User TimeSheet</label>
    <nameField>
        <displayFormat>UTS-{00000000}</displayFormat>
        <label>User TimeSheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users TimeSheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vacation_Days__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Vacation Days</relationshipLabel>
        <relationshipName>Vacation_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacation_Day__c</fullName>
        <label>Vacation Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Vacation Day</label>
    <nameField>
        <displayFormat>VD-{0000}</displayFormat>
        <label>Vacation Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EE_UserTimeSheetExtension.cls
public with sharing class EE_UserTimeSheetExtension {

	public final User_TimeSheet__c userTimeSheet {get;set;}

    public final ApexPages.StandardController standardController{get;set;}

    public TimeSheet__c timeSheet {get;set;}

    public Set<Integer> vacationDays;

    public List<Company_Project__c> userProjects {get;set;}

    public Boolean mondayDisabled {get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.MONDAY)) || !timeSheet.MondayIncluded__c ? true:false;}}

    public Boolean tuesdayDisabled {get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.THURSDAY)) || !timeSheet.TuesdayIncluded__c ? true:false;}}

    public Boolean wednesdayDisabled {get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.WEDNESDAY)) || !timeSheet.WednesdayIncluded__c ? true:false;}}

    public Boolean thursdayDisabled {get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.THURSDAY)) || !timeSheet.ThursdayIncluded__c ? true:false;}}

    public Boolean fridayDisabled {get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.FRIDAY)) || !timeSheet.FridayIncluded__c ? true:false;}}

    public Boolean saturdayDisabled { get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.SATURDAY)) || !timeSheet.SaturdayIncluded__c ? true:false;}}

    public Boolean sundayDisabled {get{ return (vacationDays != null && vacationDays.contains(EE_UTL_DateUtils.SUNDAY)) || !timeSheet.SundayIncluded__c ? true:false;}}
    
    private final List<WeekDay> orderedDays = new List<WeekDay>{
        new WeekDay('Monday','Monday_Hours__c'),
        new WeekDay('Tuesday','Tuesday_Hours__c'),
        new WeekDay('Wednesday','Wednesday_Hours__c'),
        new WeekDay('Thursday','Thursday_Hours__c'),
        new WeekDay('Friday','Friday_Hours__c'),
        new WeekDay('Saturday','Saturday_Hours__c'),
        new WeekDay('Sunday','Sunday_Hours__c') 
    };
    
    public EE_UserTimeSheetExtension(ApexPages.StandardController stdController) {
        this.standardController = stdController;
        this.standardController.addFields(new String[]{
            'Friday_Hours__c',
            'Monday_Hours__c',
            'Overhours_Allowed__c',
            'Project_Id__c',
            'Saturday_Hours__c',
            'Sunday_Hours__c',
            'Thursday_Hours__c',
            'TimeSheet__c',
            'Tuesday_Hours__c',
            'User__c',
            'User_Comment__c',
            'Wednesday_Hours__c'  

        });


        this.userTimeSheet = (User_TimeSheet__c)stdController.getRecord(); 
        Id timeSheetId = ApexPages.currentPage().getParameters().get('tsId'); 

        if(String.isBlank(this.userTimeSheet.TimeSheet__c )){
            this.userTimeSheet.TimeSheet__c = timeSheetId;         
        }

        timeSheet = EE_DAO_TimeSheetDao.getById(this.userTimeSheet.TimeSheet__c);        
        calculateVacationDays();
        userProjects = getProjectsForUser(UserInfo.getUserId());
    }   

    public List<WeekDay> getOrderedDays(){
        return orderedDays;
    }

    public List<SelectOption> getItems(){
        List<SelectOption> options = new List<SelectOption>();
        for(Integer hour= 0; hour <= 24; hour ++ ){
            String hourOption = String.valueOf(hour); 
            options.add(new SelectOption(hourOption,hourOption));
        }

        return options;
    }

    public List<SelectOption> getProjectItems(){
        List<SelectOption> options = new List<SelectOption>();
        for(Company_Project__c project:userProjects){
            options.add(new SelectOption(project.Id,project.Name));
        }

        return options;
    }

    private void calculateVacationDays(){
        vacationDays = new Set<Integer>();
        List<Vacation_Days__c> days = [SELECT Country__c,Vacation_Day__c FROM Vacation_Days__c WHERE  TimeSheet__c=:timeSheet.ID]; 

        for(Vacation_Days__c vacationDay:days){
            Integer startDateDayOfWeek = EE_UTL_DateUtils.getDayOfWeek(timeSheet.StartDay__c);
            Integer daysBetween = timeSheet.StartDay__c.daysBetween(vacationDay.Vacation_Day__c);
            vacationDays.add(startDateDayOfWeek + daysBetween);
        }
    }

    private void validateDays(){
        sObject userTsObject = (sObject) this.userTimeSheet;

        for(WeekDay day:orderedDays){
            if(userTsObject.get(day.fieldName) == null){
                userTsObject.put(day.fieldName,0);
            }
        }
    }

    public PageReference saveUserTimeSheet(){
        validateDays();
        this.standardController.save();

        return null;
    }

    private class WeekDay{
        public String label {get;set;}
        public String fieldName {get;set;}

        public WeekDay(String label,String fieldName){
            this.label = label;
            this.fieldName = fieldName;
        }
    }

    public List<Company_Project__c> getProjectsForUser(Id userId){
       List<Company_Project_Assigment__c> assigments = [SELECT ID,Project__r.Name,Project__r.Id FROM Company_Project_Assigment__c WHERE User__c = :userId];
       List<Company_Project__c> projects = new List<Company_Project__c>();
       for(Company_Project_Assigment__c assigment:assigments){
            projects.add(assigment.Project__r);
       }

       return projects;
    }
    
}