src/objects/TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>ConnectedTimeSheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>TimeSheet</relationshipLabel>
        <relationshipName>TimeSheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DaysInPeriod__c</fullName>
        <formula>EndDate__c -  StartDay__c</formula>
        <label>Days In Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FridayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MondayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProcessId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>ProcessId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ReportTime__c</fullName>
        <label>Report Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SaturdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDay__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SundayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ThursdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TuesdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WednesdayIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday Included</label>
        <type>Checkbox</type>
    </fields>
    <label>TimeSheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_TimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Friday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Friday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Monday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overhours_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overhours Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previously_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Previously Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Saturday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Saturday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sunday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thursday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Thursday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TimeSheet__c</fullName>
        <label>TimeSheet</label>
        <referenceTo>TimeSheet__c</referenceTo>
        <relationshipLabel>Users TimeSheets</relationshipLabel>
        <relationshipName>Users_TimeSheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tuesday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tuesday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Comment__c</fullName>
        <label>User Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Users_TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wednesday_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Wednesday Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User TimeSheet</label>
    <nameField>
        <displayFormat>UTS-{00000000}</displayFormat>
        <label>User TimeSheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users TimeSheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EE_DAO_TimeSheetDao.cls
public class EE_DAO_TimeSheetDao {

	public static Database.SaveResult save(TimeSheet__c timeSheet){	
		Database.SaveResult result; 
		if(String.isNotBlank(timeSheet.ID)){
			result = Database.update(timeSheet);
		}else{
			result = Database.insert(timeSheet);
		}

		return result;
	}

	public static TimeSheet__c getById(Id timeSheetId){
		List<TimeSheet__c> timeSheet = 
			[SELECT
				IsActive__c,
				DaysInPeriod__c,
				EndDate__c,
				FridayIncluded__c,
				MondayIncluded__c,
				ProcessId__c,
				ReportTime__c,
				SaturdayIncluded__c,
				StartDay__c,
				SundayIncluded__c,
				ThursdayIncluded__c,
				ConnectedTimeSheet__c,
				TuesdayIncluded__c,
				WednesdayIncluded__c
			FROM 
				TimeSheet__c
			WHERE
				Id = :timeSheetId
			];

		return timeSheet != null && !timeSheet.isEmpty() ? timeSheet[0] : null;
	}

	public static TimeSheet__c getByDate(Date currentDate){
		List<TimeSheet__c> timeSheet = 
			[SELECT
				IsActive__c,
				DaysInPeriod__c,
				EndDate__c,
				FridayIncluded__c,
				MondayIncluded__c,
				ProcessId__c,
				ReportTime__c,
				SaturdayIncluded__c,
				StartDay__c,
				SundayIncluded__c,
				ThursdayIncluded__c,
				ConnectedTimeSheet__c,
				TuesdayIncluded__c,
				WednesdayIncluded__c
			FROM 
				TimeSheet__c
			WHERE
				StartDay__c >= :currentDate AND EndDate__c <= :currentDate
			];

		return timeSheet != null && !timeSheet.isEmpty() ? timeSheet[0] : null;	
	}

	public static TimeSheet__c getWithChildrenById(Id timeSheetId){
		List<TimeSheet__c> timeSheet = 
			[SELECT
				IsActive__c,
				DaysInPeriod__c,
				EndDate__c,
				FridayIncluded__c,
				MondayIncluded__c,
				ProcessId__c,
				ReportTime__c,
				SaturdayIncluded__c,
				StartDay__c,
				SundayIncluded__c,
				ThursdayIncluded__c,
				ConnectedTimeSheet__c,
				TuesdayIncluded__c,
				WednesdayIncluded__c,
					(SELECT
					IsActive__c,
					DaysInPeriod__c,
					EndDate__c,
					FridayIncluded__c,
					MondayIncluded__c,
					ProcessId__c,
					ReportTime__c,
					SaturdayIncluded__c,
					StartDay__c,
					SundayIncluded__c,
					ThursdayIncluded__c,
					ConnectedTimeSheet__c,
					TuesdayIncluded__c,
					WednesdayIncluded__c FROM TimeSheet__r)
			FROM 
				TimeSheet__c
			WHERE
				Id = :timeSheetId
			];

		return timeSheet != null && !timeSheet.isEmpty() ? timeSheet[0] : null;
	}

	public static User_TimeSheet__c getUserTimeSheetById(ID userTimeSheetId){
		List<User_TimeSheet__c> userTimeSheets =
			[SELECT
					Friday_Hours__c,
					Monday_Hours__c,
					Overhours_Allowed__c,
					Previously_Rejected__c,
					Previously_Sent__c,
					Project_Id__c,
					Saturday_Hours__c,
					Status__c,
					Sunday_Hours__c,
					Thursday_Hours__c,
					TimeSheet__c,
					Tuesday_Hours__c,
					User__c,
					User_Comment__c,
					Wednesday_Hours__c
			FROM
				User_TimeSheet__c
			WHERE
				Id = :userTimeSheetId
			];
		return userTimeSheets != null && !userTimeSheets.isEmpty() ? userTimeSheets[0] : null;
	}
}